import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { DailyReport } from '@/types/dailyReport';
import { format } from 'date-fns';

function fmt(n: number | null, decimals = 0): string {
  if (n == null || Number.isNaN(n)) return '—';
  return decimals ? n.toFixed(decimals) : String(Math.round(n));
}

export function generateDailyReportPdf(report: DailyReport): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.getPageWidth();
  let y = 18;

  doc.setFontSize(18);
  doc.text('NeuralTrace — Daily Health Report', 14, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(80, 80, 80);
  doc.text(`Patient: ${report.patientName}`, 14, y);
  y += 6;
  doc.text(`Date: ${format(new Date(report.date), 'PPP')}`, 14, y);
  y += 6;
  doc.text(`Generated: ${format(new Date(report.generatedAt), 'PPpp')}`, 14, y);
  y += 12;

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text('Vitals summary', 14, y);
  y += 8;

  const vs = report.vitalsSummary;
  const summaryRows: string[][] = [
    ['Metric', 'Avg', 'Min', 'Max', 'Unit'],
    ['Heart rate', fmt(vs.heartRate.avg), fmt(vs.heartRate.min), fmt(vs.heartRate.max), vs.heartRate.unit],
    ['BP systolic', fmt(vs.bloodPressureSystolic.avg), fmt(vs.bloodPressureSystolic.min), fmt(vs.bloodPressureSystolic.max), vs.bloodPressureSystolic.unit],
    ['BP diastolic', fmt(vs.bloodPressureDiastolic.avg), fmt(vs.bloodPressureDiastolic.min), fmt(vs.bloodPressureDiastolic.max), vs.bloodPressureDiastolic.unit],
    ['Temperature', fmt(vs.temperature.avg, 1), fmt(vs.temperature.min, 1), fmt(vs.temperature.max, 1), vs.temperature.unit],
    ['SpO₂', fmt(vs.oxygenSaturation.avg), fmt(vs.oxygenSaturation.min), fmt(vs.oxygenSaturation.max), vs.oxygenSaturation.unit],
    ['Resp. rate', fmt(vs.respiratoryRate.avg), fmt(vs.respiratoryRate.min), fmt(vs.respiratoryRate.max), vs.respiratoryRate.unit],
  ];

  autoTable(doc, {
    startY: y,
    head: [summaryRows[0]],
    body: summaryRows.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    margin: { left: 14 },
    tableWidth: pageW - 28,
  });
  const docWithTable = doc as unknown as { lastAutoTable?: { finalY: number } };
  y = (docWithTable.lastAutoTable?.finalY ?? y) + 12;

  if (report.flaggedEvents.length > 0) {
    if (y > 240) {
      doc.addPage();
      y = 18;
    }
    doc.setFontSize(12);
    doc.text('Flagged events', 14, y);
    y += 8;
    const eventRows = report.flaggedEvents.map((e) => [
      format(new Date(e.time), 'HH:mm'),
      e.severity,
      e.explanation.slice(0, 80) + (e.explanation.length > 80 ? '…' : ''),
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Time', 'Severity', 'Explanation']],
      body: eventRows,
      theme: 'grid',
      headStyles: { fillColor: [192, 57, 43] },
      margin: { left: 14 },
      tableWidth: pageW - 28,
    });
    y = (docWithTable.lastAutoTable?.finalY ?? y) + 12;
  }

  if (report.recommendations.length > 0) {
    if (y > 250) {
      doc.addPage();
      y = 18;
    }
    doc.setFontSize(12);
    doc.text('Recommendations', 14, y);
    y += 8;
    report.recommendations.forEach((rec, i) => {
      if (y > 270) {
        doc.addPage();
        y = 18;
      }
      doc.setFontSize(10);
      doc.text(`${i + 1}. ${rec}`, 14, y);
      y += 6;
    });
    y += 6;
  }

  if (report.readings.length > 0 && report.readings.length <= 25) {
    if (y > 220) {
      doc.addPage();
      y = 18;
    }
    doc.setFontSize(12);
    doc.text('Readings', 14, y);
    y += 8;
    const readingRows = report.readings.map((r) => [
      format(new Date(r.time), 'HH:mm'),
      fmt(r.heartRate),
      `${fmt(r.bloodPressureSystolic)}/${fmt(r.bloodPressureDiastolic)}`,
      fmt(r.temperature, 1),
      fmt(r.oxygenSaturation),
      fmt(r.respiratoryRate),
    ]);
    autoTable(doc, {
      startY: y,
      head: [['Time', 'HR', 'BP', 'Temp', 'SpO₂', 'Resp']],
      body: readingRows,
      theme: 'grid',
      headStyles: { fillColor: [52, 73, 94] },
      margin: { left: 14 },
      tableWidth: pageW - 28,
      fontSize: 8,
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'This report is generated by NeuralTrace for informational purposes only. It is not a substitute for professional medical advice.',
    14,
    doc.getPageHeight() - 10
  );

  const filename = `NeuralTrace-Daily-Report-${report.patientName.replace(/\s+/g, '-')}-${report.date}.pdf`;
  doc.save(filename);
}
